name: Bug Report
description: Report a reproducible bug in FEBRUARY11
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Short description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Exact steps to reproduce the issue.
      placeholder: |
        1. Start server with ...
        2. Open dashboard ...
        3. Trigger action ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: Describe what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Errors
      description: Paste relevant backend logs or browser console output.
      render: shell

  - type: input
    id: node
    attributes:
      label: Node Version
      placeholder: "v20.x"

  - type: input
    id: obs
    attributes:
      label: OBS Version
      placeholder: "OBS 30.x"

